#!/usr/bin/env node
/**
 * send-email.mjs — Send an email-friendly HTML report via SMTP.
 *
 * Reads:
 *   data/briefing.json    (generated by gen-briefing.mjs)
 *   data/articles-slim.json (optional, for raw feed)
 *   .env                  (SMTP config)
 *
 * Generates a mobile-friendly email HTML with inline styles.
 *
 * Usage:
 *   node scripts/send-email.mjs
 *
 * Zero external dependencies (Node 22+ built-in tls).
 */

import { readFileSync, existsSync } from "node:fs";
import { connect as tlsConnect } from "node:tls";
import { getRuntimePaths } from "../lib/runtime-paths.mjs";

const PATHS = getRuntimePaths();
const BRIEFING_PATH = PATHS.briefingPath;
const SLIM_PATH = PATHS.slimArticlesPath;
const ENV_PATH = PATHS.envPath;

// ---------------------------------------------------------------------------
// .env loader
// ---------------------------------------------------------------------------

function loadEnv() {
  if (!existsSync(ENV_PATH)) {
    console.error("✗ .env 不存在，跳过邮件发送");
    process.exit(0);
  }
  const content = readFileSync(ENV_PATH, "utf-8");
  const env = {};
  for (const line of content.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq === -1) continue;
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

// ---------------------------------------------------------------------------
// Email HTML renderer — single-column, inline styles, mobile-friendly
// ---------------------------------------------------------------------------

function esc(s) {
  return String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const DOMAIN_LABELS = {
  ai: "AI", finance: "财经", politics: "政治", tech: "科技",
  society: "社会", health: "健康", entertainment: "娱乐",
  sports: "体育", science: "科学", security: "安全", auto: "汽车", general: "综合",
};

const DOMAIN_COLORS = {
  ai: "#e8f5e9", finance: "#e3f2fd", politics: "#fce4ec", tech: "#f3e5f5",
  society: "#fff3e0", health: "#e0f7fa", entertainment: "#fce4ec",
  sports: "#e8eaf6", science: "#e0f2f1", security: "#fff8e1", auto: "#efebe9", general: "#f5f5f5",
};

const DOMAIN_ACCENTS = {
  ai: "#2e7d32", finance: "#1565c0", politics: "#c62828", tech: "#7b1fa2",
  society: "#e65100", health: "#00838f", entertainment: "#ad1457",
  sports: "#283593", science: "#00695c", security: "#f57f17", auto: "#4e342e", general: "#616161",
};

function applyUnderline(text) {
  if (!text) return "";
  return esc(text).replace(/【focus_on】([^；]+)/g, '<span style="text-decoration:underline;text-decoration-color:#8b5e3c;text-underline-offset:3px;">$1</span>');
}

function renderEmailHtml(briefing) {
  const createdAt = new Date(briefing.created_at).toLocaleDateString("zh-CN", {
    year: "numeric", month: "long", day: "numeric",
  });
  const coverage = briefing.coverage || {};

  // Domain briefs
  const domains = Object.entries(briefing.domain_briefs || {}).filter(([k]) => k !== "general");
  const domainHtml = domains.map(([key, brief]) => {
    const label = DOMAIN_LABELS[key] || key;
    const bg = DOMAIN_COLORS[key] || "#f5f5f5";
    const accent = DOMAIN_ACCENTS[key] || "#616161";
    const text = applyUnderline(brief);
    return `
      <div style="margin-bottom:12px;padding:12px 16px;background:${bg};border-radius:8px;">
        <div style="font-size:12px;font-weight:700;color:${accent};margin-bottom:6px;letter-spacing:0.5px;">${label}</div>
        <div style="font-size:14px;line-height:1.7;color:#333;">${text}</div>
      </div>`;
  }).join("");

  // Raw articles (optional)
  let rawHtml = "";
  try {
    if (existsSync(SLIM_PATH)) {
      const articles = JSON.parse(readFileSync(SLIM_PATH, "utf-8"));
      // Group by source
      const sourceMap = new Map();
      for (const a of articles) {
        const src = a.source || "未知来源";
        if (!sourceMap.has(src)) sourceMap.set(src, []);
        sourceMap.get(src).push(a);
      }
      const entries = [...sourceMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));
      rawHtml = entries.map(([src, arts]) => {
        const items = arts.map((a) => {
          const title = a.title_cn ? esc(a.title_cn) : esc(a.title);
          const titleAttr = a.title_cn ? ` title="${esc(a.title)}"` : "";
          const date = a.date ? new Date(a.date).toLocaleDateString("zh-CN", { month: "short", day: "numeric" }) : "";
          return `
            <div style="padding:6px 0;border-bottom:1px solid #f0f0f0;">
              <a href="${esc(a.link)}" style="font-size:13px;color:#8b5e3c;text-decoration:none;"${titleAttr}>${title}</a>
              ${date ? `<span style="font-size:11px;color:#999;margin-left:8px;">${date}</span>` : ""}
            </div>`;
        }).join("");
        return `
          <div style="margin-bottom:14px;">
            <div style="font-size:12px;font-weight:700;color:#666;margin-bottom:4px;padding-bottom:4px;border-bottom:1px solid #e0e0e0;">${esc(src)} <span style="font-weight:400;color:#999;">(${arts.length})</span></div>
            ${items}
          </div>`;
      }).join("");
    }
  } catch { /* skip raw feed */ }

  // Compose
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f1e8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif;">
<center style="width:100%;background:#f4f1e8;padding:20px 0;">

<!-- Header -->
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;"><tr><td style="padding:0 16px;">
  <div style="text-align:center;padding:24px 0 16px;">
    <h1 style="margin:0;font-size:24px;color:#1d1b18;">News Push</h1>
    <p style="margin:6px 0 0;font-size:13px;color:#888;">${esc(createdAt)} · 处理文章 ${coverage.articles_count || 0}</p>
  </div>
</td></tr></table>

<!-- Global Brief -->
<!-- Domain Briefs (今日速览) -->
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;"><tr><td style="padding:0 16px;">
  <div style="background:#fffdf8;border:1px solid #ddd2c4;border-radius:12px;padding:16px 20px;margin-bottom:16px;">
    <div style="font-size:12px;font-weight:700;color:#8b5e3c;margin-bottom:12px;letter-spacing:1px;">今日速览</div>
    ${domainHtml}
  </div>
</td></tr></table>

<!-- Raw Feed -->
${rawHtml ? `<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;"><tr><td style="padding:0 16px;">
  <div style="background:#fffdf8;border:1px solid #ddd2c4;border-radius:12px;padding:16px 20px;margin-bottom:24px;">
    <div style="font-size:12px;font-weight:700;color:#8b5e3c;margin-bottom:12px;letter-spacing:1px;">原始订阅信息流</div>
    ${rawHtml}
  </div>
</td></tr></table>` : ""}

<!-- Footer -->
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;"><tr><td style="padding:0 16px;">
  <div style="text-align:center;padding:12px 0 24px;font-size:11px;color:#bbb;">
    News Push · Powered by Claude Code
  </div>
</td></tr></table>

</center>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Minimal SMTP client over TLS (port 465)
// ---------------------------------------------------------------------------

function smtpConnect(host, port) {
  return new Promise((resolve, reject) => {
    const socket = tlsConnect({ host, port, rejectUnauthorized: true }, () => resolve(socket));
    socket.on("error", reject);
    socket.setTimeout(30_000, () => { socket.destroy(); reject(new Error("连接超时")); });
  });
}

function readResponse(socket) {
  return new Promise((resolve, reject) => {
    let buf = "";
    const onData = (chunk) => {
      buf += chunk.toString();
      const lines = buf.split("\r\n");
      const last = lines[lines.length - 2] || lines[lines.length - 1];
      if (/^\d{3}\s/.test(last)) {
        socket.off("data", onData);
        resolve(buf);
      }
    };
    socket.on("data", onData);
    setTimeout(() => { socket.off("data", onData); resolve(buf); }, 10_000);
  });
}

async function sendCmd(socket, cmd) {
  socket.write(cmd + "\r\n");
  const resp = await readResponse(socket);
  const code = parseInt(resp.trim().slice(0, 3), 10);
  if (code >= 400) throw new Error(`SMTP 错误: ${cmd.split(" ")[0]} → ${resp.trim()}`);
  return resp;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const env = loadEnv();

  const host = env.SMTP_HOST;
  const port = parseInt(env.SMTP_PORT || "465", 10);
  const user = env.SMTP_USER;
  const pass = env.SMTP_PASS;
  const to = env.EMAIL_TO;

  if (!host || !user || !pass || !to) {
    console.error("✗ .env 配置不完整，需要: SMTP_HOST, SMTP_USER, SMTP_PASS, EMAIL_TO");
    process.exit(1);
  }

  if (!existsSync(BRIEFING_PATH)) {
    console.error("✗ briefing.json 不存在，请先生成报告");
    process.exit(1);
  }

  const briefing = JSON.parse(readFileSync(BRIEFING_PATH, "utf-8"));
  const html = renderEmailHtml(briefing);
  const today = new Date().toLocaleDateString("zh-CN", { year: "numeric", month: "long", day: "numeric" });
  const toList = to.split(",").map((e) => e.trim()).filter(Boolean);

  console.log(`→ 连接 SMTP: ${host}:${port}`);

  const socket = await smtpConnect(host, port);
  await readResponse(socket);
  await sendCmd(socket, `EHLO localhost`);
  await sendCmd(socket, "AUTH LOGIN");
  await sendCmd(socket, Buffer.from(user).toString("base64"));
  await sendCmd(socket, Buffer.from(pass).toString("base64"));
  await sendCmd(socket, `MAIL FROM:<${user}>`);
  for (const recipient of toList) {
    await sendCmd(socket, `RCPT TO:<${recipient}>`);
  }
  await sendCmd(socket, "DATA");

  const headers = [
    `From: News Push <${user}>`,
    `To: ${toList.join(", ")}`,
    `Subject: =?UTF-8?B?${Buffer.from(`News Push · ${today}`).toString("base64")}?=`,
    `Date: ${new Date().toUTCString()}`,
    "MIME-Version: 1.0",
    `Content-Type: text/html; charset=UTF-8`,
    "Content-Transfer-Encoding: base64",
    "",
  ].join("\r\n");

  const encoded = Buffer.from(html).toString("base64").match(/.{1,76}/g).join("\r\n");
  socket.write(headers + "\r\n" + encoded + "\r\n.\r\n");
  const sendResp = await readResponse(socket);
  const sendCode = parseInt(sendResp.trim().slice(0, 3), 10);
  if (sendCode >= 400) throw new Error(`发送失败: ${sendResp.trim()}`);

  socket.write("QUIT\r\n");
  socket.end();

  console.log(`✓ 邮件已发送至: ${toList.join(", ")}`);
}

main().catch((err) => {
  console.error("✗ 发送失败:", err.message);
  process.exit(1);
});
